baseURL = "https://klavdiy.github.io/"
defaultContentLanguage = "ru"
locale = "ru"
title = "Блог Клавдия - консультанта по кибербезопасности"

theme = "anatole"

summaryLength = 30
enableEmoji = true
enableRobotsTXT = true
cleanDestinationDir = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

localizedDates = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = "keywords"
  weight = 100
[[related.indices]]
  name = "tags"
  weight = 80
